id: 6484cb90145241f5b22933e3492bb495
initial_creation_type: ocr
source_metadata:
  volumes:
    f1e1612135314cd2831efbc005d4ca08:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
